services:
  postgres16:
    image: postgres:16
    container_name: postgres16
    restart: always
    ports:
      - "5432:5432" # Expor a porta 5432 para acesso externo e de outros contêineres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência dos dados

  minio:
    image: minio/minio:latest # Use a tag específica se necessário
    container_name: minio
    restart: always
    ports:
      - "9010:9000" # Porta da API (alterada para evitar conflitos)
      - "9011:9001" # Porta do Console (alterada para evitar conflitos)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    volumes:
      - minio_data:/data # Volume para persistência dos dados do MinIO
    command: server /data --console-address ":9001"

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    container_name: typebot-builder
    restart: always
    ports:
      - "${BUILDER_PORT}:3000" # Porta do Builder
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DATABASE_URL: ${TYPEBOT_DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      # Credenciais de autenticação
      NEXTAUTH_SECRET: ${ENCRYPTION_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      # Configurações de email
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_FROM: ${NEXT_PUBLIC_SMTP_FROM}
      # Configurações do S3/MinIO
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PORT: ${S3_PORT}
      S3_REGION: ${S3_REGION}
      S3_SSL: ${S3_SSL}
    volumes:
      - typebot_builder_data:/typebot/builder/.next/cache
    depends_on:
      - postgres16
      - minio

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    container_name: typebot-viewer
    restart: always
    ports:
      - "${VIEWER_PORT}:3000" # Porta do Viewer
    environment:
      DATABASE_URL: ${TYPEBOT_DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      # Configurações do S3/MinIO
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PORT: ${S3_PORT}
      S3_REGION: ${S3_REGION}
      S3_SSL: ${S3_SSL}
    volumes:
      - typebot_viewer_data:/typebot/viewer/.next/cache
    depends_on:
      - postgres16
      - minio

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "6379:6379"

  evolutionapi:
    image: atendai/evolution-api:homolog
    container_name: evolutionapi
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      DATABASE_URL: ${EVOLUTION_DATABASE_URL}
      DATABASE_ENABLED: true
      DATABASE_CONNECTION_URI: ${EVOLUTION_DATABASE_URL}
      DATABASE_CONNECTION_DB_PREFIX_TABLE: false
      DATABASE_SAVE_DATA_INSTANCE: true
      DATABASE_SAVE_DATA_OLD_MESSAGE: true
      DATABASE_SAVE_MESSAGE_UPDATE: true
      DATABASE_SAVE_DATA_CONTACTS: true
      DATABASE_SAVE_DATA_CHATS: true

      # Authentication Configuration
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY}

      # Webhook Configuration
      WEBHOOK_URL: ${WEBHOOK_URL}
      GLOBAL_WEBHOOK_URL: ${WEBHOOK_URL}

      # Redis Configuration
      REDIS_URI: redis://redis:6379

      # Additional Security Settings
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      CORS_METHODS: "GET,POST,PUT,DELETE"
      CORS_CREDENTIALS: true

      # Instance Configuration
      DEL_INSTANCE: false
      DEL_TEMP_INSTANCES: true

      # Log Configuration
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_COLOR: true

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    depends_on:
      - postgres16
      - redis
    networks:
      - evolution_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  minio_data: # Volume para o MinIO
  typebot_builder_data: # Volume para o Typebot Builder
  typebot_viewer_data: # Volume para o Typebot Viewer
  evolution_instances: # Volume para as instâncias da Evolution API
  evolution_redis: # Volume para o Redis
  evolution_store:
    # Volume para o armazenamento da Evolution API

networks:
  evolution_network:
    driver: bridge
